console.log("Day 3");
console.log("Part 1");
let string ="10";
let a = 20;
let b = 40;
let sum = Number(string) + a + b;
let sum2 = a + b + string;
console.log(sum);
console.log(typeof sum);
console.log(sum2);
console.log(typeof sum2);
const num1 = prompt("Enter first number");
const num2 = prompt("Enter second number");
const add = parseInt(num1) + parseInt(num2);
const sub = parseInt(num1) - parseInt(num2);
const mul = parseInt(num1) * parseInt(num2);
console.log(add);
console.log(sub);
console.log(mul );
